dialogo1adait= Maestro, maestro! Guardate, Maestro, sono arrivata alla soluzione! Questo è il risultato del mio lavoro, credo che ora l'algoritmo sia corretto, finalmente...
dialogo1augustoit= Mhhh... fammi vedere se è davvero giusto, ma non sperare troppo. Il tuo lavoro, per quanto sia impegno e sforzo, potrebbe non essere all'altezza.
dialogo2adait= Ma... perché me l'ha strappato!? Ho impiegato settimane su questa soluzione, ho lavorato giorno e notte! E ora... ora lo butta via come se non valesse nulla!
dialogo2augustoit= Non mi interessa. Sei una donna, e in questo campo, nonostante tutti i tuoi sforzi, non avrai mai successo. La matematica, la scienza, la logica... sono territori per menti ben più elevate, menti forti. Non capisci, non ti appartengono. Inutile che ti ostini a voler entrare in questo mondo. Potresti creare scalpore, il mondo non è pronto! Assegnerò questo compito ad un uomo, saprá riscrivere i tuoi codici e finalmente pubblicherá l'algoritmo!
audio=Audio:
lingua=Lingua:

inizio=inizio
impostazioni=impostazioni
esci=impostazioni