dialogo1ada= Maestro, maestro! Guardate, Maestro, sono arrivata alla soluzione! Questo è il risultato del mio lavoro, credo che ora l'algoritmo sia corretto, finalmente...
dialogo1augusto= Mhhh... fammi vedere se è davvero giusto, ma non sperare troppo. Il tuo lavoro, per quanto sia impegno e sforzo, potrebbe non essere all'altezza.
dialogo2ada= Ma... perché me l'ha strappato!? Ho impiegato settimane su questa soluzione, ho lavorato giorno e notte! E ora... ora lo butta via come se non valesse nulla!
dialogo2augusto=La matematica, la scienza, la logica... sono territori per menti ben più elevate, menti forti. Non capisci, non ti appartengono. Inutile che ti ostini a voler entrare in questo mondo. Potresti creare scalpore, il mondo non è pronto! Assegnerò questo compito ad un uomo.
audio=Audio:
lingua=Lingua:
sottotitolo:Aiuta Ada a costruire il suo algoritmo!

inizio=Inizio
impostazioni=Impostazioni
esci=Esci